stages:
  data_ingestion:
    cmd: python src/DeepClassifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/DeepClassifier/pipeline/stage_01_data_ingestion.py
      - configs/config.yaml
    outs:
      - artifacts/data_ingestion/PetImages

  prepare_base_model:
    cmd: python src/DeepClassifier/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/DeepClassifier/pipeline/stage_02_prepare_base_model.py
      - configs/config.yaml
    params:
      - IMAGE_SIZE
      - LEARNING_RATE
      - INCLUDE_TOP
      - WEIGHTS
      - CLASSES
    outs:
      - artifacts/prepare_base_model

  training:
    cmd: python src/DeepClassifier/pipeline/stage_03_training.py
    deps:
      - src/DeepClassifier/pipeline/stage_03_training.py
      - src/DeepClassifier/components/prepare_callbacks.py
      - configs/config.yaml
      - artifacts/data_ingestion/PetImages
      - artifacts/prepare_base_model
    params:
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
      - IMAGE_SIZE
      - VALIDATION_SPLIT
      - ROTATION_RANGE
      - HORIZONTAL_FLIP
      - WIDTH_SHIFT_RANGE
      - HEIGHT_SHIFT_RANGE
      - SHEAR_RANGE
      - ZOOM_RANGE
    outs:
      - artifacts/training/model.h5

  evaluation:
    cmd: python src/DeepClassifier/pipeline/stage_04_evaluation.py
    deps:
      - src/DeepClassifier/pipeline/stage_04_evaluation.py
      - configs/config.yaml
      - artifacts/data_ingestion/PetImages
      - artifacts/training/model.h5
    params:
      - BATCH_SIZE
      - IMAGE_SIZE
      - VALIDATION_SPLIT
    metrics:
      - scores.json:
          cache: false