AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3]  # as per the VGG16 model
BATCH_SIZE: 16
INCLUDE_TOP: False
EPOCHS: 1
CLASSES: 2
WEIGHTS: imagenet  # weights of VGG16 trained on the imagenet dataset
LEARNING_RATE: 0.01