AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3]  # as per the VGG16 model
BATCH_SIZE: 16
INCLUDE_TOP: False
EPOCHS: 1
CLASSES: 2
WEIGHTS: imagenet  # weights of VGG16 trained on the imagenet dataset
LEARNING_RATE: 0.01
VALIDATION_SPLIT: 0.2
ROTATION_RANGE: 40
HORIZONTAL_FLIP: True
WIDTH_SHIFT_RANGE: 0.2
HEIGHT_SHIFT_RANGE: 0.2
SHEAR_RANGE: 0.2
ZOOM_RANGE: 0.2